FusionWeb/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FusionWeb.Data;
using FusionWeb.Models;

namespace FusionWeb.Controllers
{
    public class ContactsController : Controller
    {
        private readonly FusionWebContext _context;

        public ContactsController(FusionWebContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contact.Include(x => x.InfoClient).ToListAsync());
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.Include(x => x.InfoClient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Content")] Contact contact, Client client)
        {
            //popup for contact
            ViewData["Contact"] = "Order";

            var existclient = _context.Client.FirstOrDefault(c => c.Id == client.Id);
            if (existclient == null)
            {
                _context.Client.Add(client);
                _context.SaveChanges();

            }
           
                contact.InfoClient = client;
                _context.Contact.Add(contact);
                _context.SaveChanges();

            return View(contact);
        }


        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var contact = await _context.Contact.FindAsync(id);
        //    if (contact == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(contact);
        //}

        //// POST: Contacts/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]

        //public async Task<IActionResult> Edit(int id, [Bind("Id,Content")] Contact contact)
        //{
        //    if (id != contact.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(contact);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ContactExists(contact.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(contact);
        //}

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.Include(x => x.InfoClient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.Contact.FindAsync(id);
            _context.Contact.Remove(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
            return _context.Contact.Any(e => e.Id == id);
        }
    }
}

FusionWeb/Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FusionWeb.Data;
using FusionWeb.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace FusionWeb.Controllers
{
    public class DishesController : Controller
    {
        private readonly FusionWebContext _context;

        public DishesController(FusionWebContext context)
        {
            _context = context;
        }

        // GET: Dishes
        
        public async Task<IActionResult> Index()
        {
            var dishes = from d in _context.Dish
                                  orderby d.KitchenDish ascending
                                  select d;

            return View(await dishes.ToListAsync());

        }

        // GET: DishesCart
        public async Task<IActionResult> Cart()
        {

            string cart = HttpContext.Session.GetString("Cart"); //creat cart for evert client
            var dishes = new List<Dish>();
            if (cart != null)
            {
                string[] dishIds = cart.Split(",", StringSplitOptions.RemoveEmptyEntries);

                //Check which ID I chose in the order is equal to the ID in the DB 
                //and I will put it in a "dishes" which is a packet list
                dishes = _context.Dish.Where(x => dishIds.Contains(x.Id.ToString())).ToList();

                Dictionary<string, int> dict = new Dictionary<string, int>();
                foreach (var id in dishIds)
                {
                    if (dict.ContainsKey(id))
                        dict[id]++;
                    else
                        dict.Add(id, 1);
                }

                ViewData["quantity"] = dict;
            }
            return View(dishes);

        }

        public async Task<IActionResult> AddToCart(int id)
        {
                string cart = HttpContext.Session.GetString("Cart");
                if (cart == null)
                    cart = "";

                cart += id + ",";
                HttpContext.Session.SetString("Cart", cart);

                return RedirectToAction("Cart");
        }

        public async Task<IActionResult> Kitchen(int Id)
        {
            //dish2 = dishes from the same KitchenId;
            var dish2 = from dish in _context.Dish
                        where dish.KitchenDish == Id
                        select dish;

            return View("Index", await dish2.ToListAsync());
        }

        public async Task<IActionResult> Search()
        {

            return View(await _context.Dish.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Search(string Input)
        {

            int number = 0;
            if(int.TryParse(Input, out number))
            {
                 var d = from dish in _context.Dish
                        where dish.Price < number
                        select dish;

                if (d.Count() == 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                    return View(await d.ToListAsync());
            }
            else {

                var d1 = from dish in _context.Dish
                         where dish.Name.Contains(Input)
                         orderby dish.Name descending, dish.Price descending
                         select dish;

                if (d1.Count() == 0)
                {
                    return RedirectToAction(nameof(Index));

                }
                else
                    return View(await d1.ToListAsync());
            }
        }

        // GET: Dishes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dish
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // GET: Dishes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dishes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Description,Image,KitchenDish")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dish);
        }

        // GET: Dishes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dish.FindAsync(id);
            if (dish == null)
            {
                return NotFound();
            }
            return View(dish);
        }

        // POST: Dishes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Description,KitchenDish,Image")] Dish dish)
        {
            if (id != dish.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DishExists(dish.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dish);
        }

        // GET: Dishes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dish
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dish == null)
            {
                return NotFound();
            }

            return View(dish);
        }

        // POST: Dishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dish = await _context.Dish.FindAsync(id);
            _context.Dish.Remove(dish);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DishExists(int id)
        {
            return _context.Dish.Any(e => e.Id == id);
        }
    }
}

FusionWeb/Controllers/ManagersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FusionWeb.Data;
using FusionWeb.Models;
using Microsoft.AspNetCore.Http;

namespace FusionWeb.Controllers
{
    public class ManagersController : Controller
    {
        private readonly FusionWebContext _context;

        public ManagersController(FusionWebContext context)
        {
            _context = context;
        }

        // GET: Managers
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("user") == null)
            {
                return RedirectToAction(nameof(LogIn));
            }

            return View(await _context.Manager.ToListAsync());
        }

        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost][ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn([Bind("Id,UserName,Password")] Manager manager)
        {
            var q = from m in _context.Manager
                    where manager.UserName.Contains("levona") && m.UserName.Contains("levona") &&
                          manager.Password == m.Password
                    select m;

            if (q.Count() > 0)
            {
                HttpContext.Session.SetString("user", q.First().FullName);
                return RedirectToAction("Index","Home");
            }
            else
            {
                ViewData["Error"] = "משתמש/סיסמא לא קיים";
            }

            return View(manager);
        }





        // GET: Managers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manager = await _context.Manager
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manager == null)
            {
                return NotFound();
            }

            return View(manager);
        }

        // GET: Managers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Managers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Password,FullName")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manager);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(LogIn));
            }
            return View(manager);
        }


        
        // GET: Managers/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var manager = await _context.Manager.FindAsync(id);
        //    if (manager == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(manager);
        //}

        // POST: Managers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Password,FullName")] Manager manager)
        //{
        //    if (id != manager.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(manager);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ManagerExists(manager.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(manager);
        //}

        // GET: Managers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manager = await _context.Manager
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manager == null)
            {
                return NotFound();
            }

            return View(manager);
        }

        // POST: Managers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manager = await _context.Manager.FindAsync(id);
            _context.Manager.Remove(manager);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManagerExists(int id)
        {
            return _context.Manager.Any(e => e.Id == id);
        }
    }
}

FusionWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FusionWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/css/Layout/navbar.css" />
    <link rel="stylesheet" href="~/css/Layout/template.css" />

    @RenderSection("Css", required: false)


</head>
<body>
    <div class="container top">
        <nav class="navbar navbar-expand-lg navbar-dark ">
            <a class="navbar-brand logo" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/imag/LOGO-FUSION-Transparent-for-Web.png" id="logo">
            </a>
            @if (Context.Session.GetString("user") != null)
            {

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            }
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Contacts" asp-action="Create">צור קשר </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="RestGallery">גלריה</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="AboutUs">אודות</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Reservations" asp-action="Create">הזמנת מקום</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Dishes" asp-action="Index">משלוח</a>
                    </li>
                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" asp-area=""
                           asp-controller="Home" asp-action="Menu">
                            תפריט
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item active" asp-area="" asp-controller="Home" asp-action="Menu">ישראלי</a>
                            <a class="dropdown-item active" asp-area="" asp-controller="Home" asp-action="Menu">אמריקאי</a>
                            <a class="dropdown-item active" asp-area="" asp-controller="Home" asp-action="Menu">איטלקי</a>
                            <a class="dropdown-item active" asp-area="" asp-controller="Home" asp-action="Menu">אסיאתי</a>
                        </div>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">ראשי</a>
                    </li>
                    <li class="nav-item">
                    </li>
                    &nbsp;&nbsp;


                    <a class="sign-in" asp-area="" asp-controller="Managers" asp-action="Create">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M10 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                        </svg>
                    </a>
                </ul>
            </div>
        </nav>



    </div>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                <div class="row         AnnouncementBar__Content">
                    <div class="footer_details ">
                        <div class="footer_details_map col-sm-3 col-md-3 col-lg-3">
                            <iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6783.357038001982!2d35.225888576795576!3d31.77925307513867!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x150329d2495bf905%3A0xe5fd457b5405ec57!2z157XnteZ15zXkCwg15nXqNeV16nXnNeZ150!5e0!3m2!1siw!2sil!4v1609359668548!5m2!1siw!2sil" width="150" height="" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                        </div>

                        <div class="footer_details_contact col-sm-3 col-md-3 col-lg-3">
                            <h2 class="footer_details_contact-titel"> צור קשר</h2>
                            <h4 class="footer_details_contact-content">
                                <label class="footer_details_contact-content-fax">פקס:031234567/א</label>
                                <label class="footer_details_contact-content-phone">091234567:טלפון</label>
                                <label class="footer_details_contact-content-email">Fusion@gmail.com:אימייל</label>
                            </h4>
                        </div>

                        <div class="footer_details_address col-sm-3 col-md-3 col-lg-3">
                            <h2 class="footer_details_address-titel">כתובת </h2>
                            <h4 class="footer_details_address-content"> ממילא ירושלים</h4>
                        </div>

                    </div>
                </div>
            </div>
        </footer>*@

    @*<footer class="border-top footer text-muted">*@

    @*.footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        text-align: center;
        }

            class=AnnouncementBar__Content
    *@

    <!-- <span class="row">

        <span class="col-sm-7 col-md-5 col-lg-4 left">
            <label><h2>צור קשר </h2></label>

            <label><h4> 091234567:טלפון</h4></label>

            <label><h4>פקס:031234567/א</h4></label>
            <label><h4>Fusion@gmail.com:אימייל</h4></label>
        </span>


        <span class="col-sm-7 col-md-5 col-lg-3 center">
            <label><h2>כתובת </h2></label>

            <label><h4> ממילא ירושלים</h4></label>
        </span>


        <span class="col-sm-1 col-md-2 col-lg-5 right">

            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6783.357038001982!2d35.225888576795576!3d31.77925307513867!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x150329d2495bf905%3A0xe5fd457b5405ec57!2z157XnteZ15zXkCwg15nXqNeV16nXnNeZ150!5e0!3m2!1siw!2sil!4v1605870851249!5m2!1siw!2sil" class="map" width="200" height="200" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>


        </span>


    </span>-->
    @*</footer>*@



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)


</body>

<script>
    $('.dropdown-toggle').dropdown()
</script>


</html>